namespace Project_Info
{
    class Program
    {
        static void Main(string[] args)
        {
            QRCode.InitializeAlphaNumericTable();
            //var test = Functions.ReadImage("../../../images/Test.bmp");
            var bjr = Functions.ConvertIntToBinaryArray(1);
            //var QRTest = new QRCode(1, 0, 1, 5, 1, "NIQUE TA RACE");
            var QRTest = new QRCode("NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE NIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLENIQUE TA RACE COMMENT CA VA? JE PENSE QUE ILANA EST LA PLUS BELLE", 2);
            Functions.WriteImage(QRTest, "../../../images/Test7.bmp");
        }
    }
}